site_name: LyoPRONTO Documentation

theme:
    name: "material"
    features:
        - content.code.copy

plugins:
    - mkdocstrings:
        default_handler: python
    - mike:
        version_selector: true
        canonical_version: latest
    - ipynb
extra:
    version:
        provider: mike

markdown_extensions:
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.arithmatex:
        generic: true

extra_javascript:
# Would be nice to use KaTeX, but something isn't working right in local testing
    # - javascripts/katex.js
    # - https://unpkg.com/katex@0/dist/katex.min.js
    # - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
    - javascripts/mathjax.js
    - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Also for KaTeX
# extra_css:
#   - https://unpkg.com/katex@0/dist/katex.min.css

nav:
    # List of web pages to show, in order
    - index.md
    - tutorials.md
    - how-to-guides.md
    - Examples:
        - examples/knownRp_PD.ipynb
        - examples/unknownRp_PD.ipynb
    - explanation.md
    - reference.md
    - dev.md

