name: Publish docs to GitHub Pages
on:
  push:
    branches:
      - main
  # Delete this before merging. Currently this will overwrite the regular docs every time a pull request is made
  pull_request:


jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v5
      - run: pip install mkdocstrings-python mkdocs-material
      - name: Deploy docs
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}